"""Vendor the two UI fonts into frontend/public/fonts/.

Why this exists: the app must work in a village hall with no Wi-Fi. Loading Inter and
Noto Sans Tamil from Google's CDN means Tamil silently degrades to whatever the device
happens to have. This script downloads only the subsets the app can actually use,
rewrites the @font-face rules to point at local files, and writes fonts.css.

Both families are licensed under the SIL Open Font License 1.1, which permits
redistribution and self-hosting (see fonts/README.md for the notices).

Usage (from the frontend directory):

    python scripts/fetch-fonts.py

Re-run it to pick up new upstream versions. Commit the output: it is what makes the
offline build possible.
"""

from __future__ import annotations

import re
import sys
import urllib.request
from pathlib import Path

OUT_DIR = Path(__file__).resolve().parent.parent / "public" / "fonts"

# Subsets worth shipping. Everything else (cyrillic, greek, vietnamese, ...) is dead
# weight for an English + Tamil application.
WANTED_SUBSETS = {"latin", "latin-ext", "tamil"}

FAMILIES = [
    ("Inter", "Inter:wght@400;500;600;700"),
    ("Noto Sans Tamil", "Noto+Sans+Tamil:wght@400;500;600;700"),
]

# A modern UA is required, otherwise Google serves legacy TTF instead of woff2.
UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)

CSS_URL = "https://fonts.googleapis.com/css2?{}&display=swap".format(
    "&".join(f"family={query}" for _, query in FAMILIES)
)

# Google emits each block as:  /* subset */  @font-face { ... }
BLOCK_RE = re.compile(r"/\*\s*(?P<subset>[\w-]+)\s*\*/\s*@font-face\s*\{(?P<body>[^}]*)\}")
FIELD_RE = re.compile(r"(?P<key>[\w-]+)\s*:\s*(?P<value>[^;]+);")


def fetch(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(request, timeout=60) as response:
        return response.read()


def slugify(name: str) -> str:
    return name.lower().replace(" ", "-")


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    try:
        css = fetch(CSS_URL).decode("utf-8")
    except Exception as exc:  # noqa: BLE001 - a clear message beats a traceback here
        print(f"ERROR: could not reach Google Fonts ({exc}).")
        print("This script needs the internet once; the app itself never does.")
        return 1

    blocks: list[tuple[str, dict[str, str], str]] = []
    for match in BLOCK_RE.finditer(css):
        subset = match.group("subset")
        fields = {
            m.group("key").strip(): m.group("value").strip()
            for m in FIELD_RE.finditer(match.group("body"))
        }
        url_match = re.search(r"url\((?P<url>[^)]+)\)", fields.get("src", ""))
        if url_match is None:
            continue
        blocks.append((subset, fields, url_match.group("url")))

    if not blocks:
        print("ERROR: no @font-face blocks found — the Google Fonts response changed shape.")
        return 1

    written: list[str] = []
    # Keep per-family order stable so the generated CSS is diff-friendly.
    out_rules: list[str] = []

    for family, _ in FAMILIES:
        family_blocks = [
            (subset, fields, url)
            for subset, fields, url in blocks
            if fields.get("font-family", "").strip("'\"") == family
        ]
        keep = [b for b in family_blocks if b[0] in WANTED_SUBSETS] or family_blocks

        for subset, fields, url in keep:
            weight = fields.get("font-weight", "400")
            filename = f"{slugify(family)}-{subset}-{weight}.woff2"
            target = OUT_DIR / filename
            if target.exists():
                print(f"  keep   {filename}")
            else:
                target.write_bytes(fetch(url))
                print(f"  fetch  {filename}  ({target.stat().st_size // 1024} KB)")
            written.append(filename)

            out_rules.append(
                "\n".join(
                    [
                        f"/* {family} · {subset} · {weight} */",
                        "@font-face {",
                        f"  font-family: '{family}';",
                        "  font-style: normal;",
                        f"  font-weight: {weight};",
                        "  font-display: swap;",
                        f"  src: url('./{filename}') format('woff2');",
                        f"  unicode-range: {fields.get('unicode-range', '')};".rstrip(),
                        "}",
                    ]
                )
            )

    header = (
        "/* Generated by frontend/scripts/fetch-fonts.py — do not edit by hand.\n"
        " * Inter and Noto Sans Tamil, self-hosted so the app renders properly offline.\n"
        " * Both are licensed under the SIL Open Font License 1.1 (see OFL.txt).\n"
        " */\n"
    )
    (OUT_DIR / "fonts.css").write_text(header + "\n" + "\n\n".join(out_rules) + "\n", encoding="utf-8")

    print(f"\n{len(written)} font files and fonts.css written to {OUT_DIR}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
