"""initial schema

Revision ID: 23500b49a33f
Revises: 
Create Date: 2026-09-20 20:07:30.341936
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '23500b49a33f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=False),
    sa.Column('title_ta', sa.String(length=200), nullable=False),
    sa.Column('summary_en', sa.Text(), nullable=False),
    sa.Column('summary_ta', sa.Text(), nullable=False),
    sa.Column('body_en', sa.Text(), nullable=False),
    sa.Column('body_ta', sa.Text(), nullable=False),
    sa.Column('red_flags_json', sa.Text(), nullable=False),
    sa.Column('safe_actions_json', sa.Text(), nullable=False),
    sa.Column('victim_steps_json', sa.Text(), nullable=False),
    sa.Column('real_example_en', sa.Text(), nullable=False),
    sa.Column('real_example_ta', sa.Text(), nullable=False),
    sa.Column('helpline', sa.String(length=120), nullable=False),
    sa.Column('tags', sa.String(length=300), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kb_articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kb_articles_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_kb_articles_slug'), ['slug'], unique=True)

    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('difficulty', sa.String(length=10), nullable=False),
    sa.Column('question_en', sa.Text(), nullable=False),
    sa.Column('question_ta', sa.Text(), nullable=False),
    sa.Column('options_en_json', sa.Text(), nullable=False),
    sa.Column('options_ta_json', sa.Text(), nullable=False),
    sa.Column('correct_index', sa.Integer(), nullable=False),
    sa.Column('explanation_en', sa.Text(), nullable=False),
    sa.Column('explanation_ta', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_questions_category'), ['category'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('preferred_language', sa.String(length=5), nullable=False),
    sa.Column('age_group', sa.String(length=20), nullable=True),
    sa.Column('locality', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('assistant_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('question_redacted', sa.Text(), nullable=False),
    sa.Column('answer_source', sa.String(length=20), nullable=False),
    sa.Column('matched_article_id', sa.Integer(), nullable=True),
    sa.Column('helpful', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['matched_article_id'], ['kb_articles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assistant_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assistant_logs_created_at'), ['created_at'], unique=False)

    op.create_table('scam_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('redacted_text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_label', sa.String(length=20), nullable=False),
    sa.Column('primary_category', sa.String(length=40), nullable=False),
    sa.Column('categories_json', sa.Text(), nullable=False),
    sa.Column('matched_rules_json', sa.Text(), nullable=False),
    sa.Column('model_confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scam_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scam_analyses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scam_analyses_primary_category'), ['primary_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_scam_analyses_risk_label'), ['risk_label'], unique=False)
        batch_op.create_index('ix_scam_created_label', ['created_at', 'risk_label'], unique=False)

    op.create_table('url_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('submitted_url_redacted', sa.String(length=600), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_label', sa.String(length=20), nullable=False),
    sa.Column('features_json', sa.Text(), nullable=False),
    sa.Column('top_reasons_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('url_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_url_checks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_url_checks_risk_label'), ['risk_label'], unique=False)

    op.create_table('workshops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=False),
    sa.Column('title_ta', sa.String(length=200), nullable=False),
    sa.Column('venue', sa.String(length=200), nullable=False),
    sa.Column('locality', sa.String(length=120), nullable=True),
    sa.Column('district', sa.String(length=120), nullable=False),
    sa.Column('conducted_on', sa.Date(), nullable=False),
    sa.Column('facilitator_id', sa.Integer(), nullable=True),
    sa.Column('audience_type', sa.String(length=40), nullable=False),
    sa.Column('participants_expected', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['facilitator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workshops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workshops_conducted_on'), ['conducted_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_workshops_district'), ['district'], unique=False)

    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('age_group', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('phone_hash', sa.String(length=64), nullable=True),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participants_workshop_id'), ['workshop_id'], unique=False)

    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('answers_json', sa.Text(), nullable=False),
    sa.Column('taken_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participant_id', 'type', name='uq_participant_assessment_type')
    )
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.create_index('ix_assessment_workshop_type', ['workshop_id', 'type'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_participant_id'), ['participant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_taken_at'), ['taken_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_workshop_id'), ['workshop_id'], unique=False)

    op.create_table('feedback_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_entries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_entries_workshop_id'), ['workshop_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_entries_workshop_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_entries_created_at'))

    op.drop_table('feedback_entries')
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessments_workshop_id'))
        batch_op.drop_index(batch_op.f('ix_assessments_taken_at'))
        batch_op.drop_index(batch_op.f('ix_assessments_participant_id'))
        batch_op.drop_index('ix_assessment_workshop_type')

    op.drop_table('assessments')
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participants_workshop_id'))

    op.drop_table('participants')
    with op.batch_alter_table('workshops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workshops_district'))
        batch_op.drop_index(batch_op.f('ix_workshops_conducted_on'))

    op.drop_table('workshops')
    with op.batch_alter_table('url_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_url_checks_risk_label'))
        batch_op.drop_index(batch_op.f('ix_url_checks_created_at'))

    op.drop_table('url_checks')
    with op.batch_alter_table('scam_analyses', schema=None) as batch_op:
        batch_op.drop_index('ix_scam_created_label')
        batch_op.drop_index(batch_op.f('ix_scam_analyses_risk_label'))
        batch_op.drop_index(batch_op.f('ix_scam_analyses_primary_category'))
        batch_op.drop_index(batch_op.f('ix_scam_analyses_created_at'))

    op.drop_table('scam_analyses')
    with op.batch_alter_table('assistant_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assistant_logs_created_at'))

    op.drop_table('assistant_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_questions_category'))

    op.drop_table('quiz_questions')
    with op.batch_alter_table('kb_articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kb_articles_slug'))
        batch_op.drop_index(batch_op.f('ix_kb_articles_category'))

    op.drop_table('kb_articles')
    # ### end Alembic commands ###
